name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/esbmc-solidity-gh-action:$RELEASE_VERSION .
          docker tag ${{ env.DOCKER_USERNAME }}/esbmc-solidity-gh-action:$RELEASE_VERSION ${{ env.DOCKER_USERNAME }}/esbmc-solidity-gh-action:latest
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/esbmc-solidity-gh-action:$RELEASE_VERSION
          docker push ${{ env.DOCKER_USERNAME }}/esbmc-solidity-gh-action:latest